### ISSUE TITLE
When running Parallel test no screenshot

### ISSUE THREAD

**Issue by Trisha1212** [azachar/screenshoter-report-analyzer#2]
my conf file : 
/**
 * config file
 */
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    rootElement: 'body',
    allScriptsTimeout: 60000,
    framework: 'jasmine',
    jasmineNodeOpts: {
        // If true, display spec names.
        isVerbose: true,
        // If true, print colors to the terminal.
        showColors: true,
        // If true, include stack traces in failures.
        includeStackTrace: true,
        // Default time to wait in ms before a test fails.
        defaultTimeoutInterval: 600000
    },
    specs: ['testSuite/testcase.js','testSuite/permissionTest.js'],
    directConnect: true,
    params: {
        host: ""
    },
    capabilities: {
        browserName: 'chrome',
        shardTestFiles: true,
        maxInstances: 2, 
        chromeOptions: {
            // Unfortunately, chrome doesn't support running in container (https://github.com/travis-ci/travis-ci/issues/938),
            // you need to start chrome with --no-sandbox argument to avoid this.
            'args': ['--disable-web-security','--no-sandbox','--disable-infobars']
         }
    },
       plugins: [{
        package: 'protractor-console',
        logLevels: ['severe'],
        package: 'protractor-screenshoter-plugin',
        screenshotPath: './REPORTS',
        screenshotOnExpect: 'failure',
        screenshotOnSpec: 'failure',
        withLogs: true,
        writeReportFreq: 'asap',
        clearFoldersBeforeTest: true
        }],
    //Onprepare function
    onPrepare: function() {
        browser.driver.manage().timeouts().implicitlyWait(10000);
         return global.browser.getProcessedConfig().then(function(config) {
              //it is ok to be empty
          });
    }
};

package.json : 
{
  "name": "dashboard-new-admin-e2e",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "webdriver-update": "webdriver-manager update",
    "test": "protractor conf.js"
  },
  "devDependencies": {
    "protractor": "^5.2.2",
    "protractor-console": "^3.0.0"
  },
  "dependencies": {
    "moment": "^2.20.0",
    "mysql": "~2.8.0",
    "protractor-screenshoter-plugin": "^0.7.0"
  }
}

Do we need to store the browserInstance : var a  = browser.forkNewDriverInstance();
var b  = browser.forkNewDriverInstance(); like this ?

**Comment by azachar** [comment]
Hi there,
 Indeed you need to store to screenshoter your forked instances, otherwise it won’t be aware of it.

Please readme in protractor screenshoter plugin, there is a detailed how to.

Cheers,
Andrej

**Comment by Trisha1212** [comment]
Hi Andrej,

Thank you for the reply : 

I changed conf file : 

/**
 * config file
 */
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    rootElement: 'body',
    allScriptsTimeout: 60000,
    framework: 'jasmine',
    jasmineNodeOpts: {
        // If true, display spec names.
        isVerbose: true,
        // If true, print colors to the terminal.
        showColors: true,
        // If true, include stack traces in failures.
        includeStackTrace: true,
        // Default time to wait in ms before a test fails.
        defaultTimeoutInterval: 600000
    },
    multiCapabilities: [
        {
        'specs': ['testSuite/applicationTestCases.js'],
        'browserName': 'chrome',
        chromeOptions: {
            'args': ['--disable-web-security', '--no-sandbox', '--disable-infobars']
         }
        },
        {
            'specs': ['testSuite/integrationTestCases.js'],
            'browserName': 'chrome',
            chromeOptions: {
                'args': ['--disable-web-security', '--no-sandbox', '--disable-infobars']
            }
        },
        {
            'specs': ['testSuite/permissionTestCases.js'],
            'browserName': 'chrome',
            chromeOptions: {
                'args': ['--disable-web-security', '--no-sandbox', '--disable-infobars']
            }
        },
        {
            'specs': ['testSuite/resetPasswordTestCases.js'],
            'browserName': 'chrome',
            chromeOptions: {
                'args': ['--disable-web-security', '--no-sandbox', '--disable-infobars']
            }
        },
        {
            'specs': ['testSuite/solutionPlaygroundTestCases.js'],
            'browserName': 'chrome',
            chromeOptions: {
                'args': ['--disable-web-security', '--no-sandbox', '--disable-infobars']
            }
        },
        {
            'specs': ['testSuite/taggingPlaygroundTestCases.js'],
            'browserName': 'chrome',
            chromeOptions: {
                'args': ['--disable-web-security', '--no-sandbox', '--disable-infobars']
            }
        },
        {
            'specs': ['testSuite/uploadDatafeedTestCases.js'],
            'browserName': 'chrome',
            chromeOptions: {
                'args': ['--disable-web-security', '--no-sandbox', '--disable-infobars']
            }
        },
    ],
    directConnect: true,
    params: {
        host: "http://10.138.0.13:18080/"
    },
    plugins: [{
        package: 'protractor-console',
        logLevels: ['severe'],
        package: 'protractor-screenshoter-plugin',
        screenshotPath: './REPORTS',
        screenshotOnExpect: 'failure',
        screenshotOnSpec: 'failure',
        withLogs: true,
        writeReportFreq: 'asap',
        clearFoldersBeforeTest: true
    }],
    
    //Onprepare function
    onPrepare: function() {
        var browser1  = browser.forkNewDriverInstance();
        global.screenshotBrowsers.browser1 = browser1;
            var browser2  = browser.forkNewDriverInstance();
        global.screenshotBrowsers.browser2 = browser2;
            var browser3  = browser.forkNewDriverInstance();
        global.screenshotBrowsers.browser3 = browser3;
            var browser4  = browser.forkNewDriverInstance();
        global.screenshotBrowsers.browser4 = browser4;
            var browser5  = browser.forkNewDriverInstance();
        global.screenshotBrowsers.browser5 = browser5;
            var browser6  = browser.forkNewDriverInstance();
        global.screenshotBrowsers.browser6 = browser6;
            var browser7  = browser.forkNewDriverInstance();
        global.screenshotBrowsers.browser7 = browser7;
                beforeAll(function() {
            global.screenshotBrowsers = {};
        });
        browser.driver.manage().timeouts().implicitlyWait(10000);
        return global.browser.getProcessedConfig().then(function(config) {

        });
    }
};

**Comment by azachar** [comment]
Hi there, 
please set it up in your test instead of onPrepare function.

Cheers,
Andrej
