### ISSUE TITLE
Extracting build informations

### ISSUE THREAD

**Issue by sebastienroux** [azachar/screenshoter-report-analyzer#3]
Hi,

In features i can read : Supports extracting build information (the report displays a build number, a branch, etc. ) for GitLab CI/CD, CircleCI and Travis.

Do you have a documentation about this ? 

Is there a way to manually fill this informations ? 
I'm working with Jenkins/Git.

Thx

**Comment by azachar** [comment]
Dear @sebastienroux,

Sure, there is a documentation how to do it + link to the code, which makes that extraction cristal clear.

Have a look here https://github.com/azachar/protractor-screenshoter-plugin#environmental-variables


Moreover, feel free to provide a PR to cover Jenkins :)

Cheers,
Andrej
